---
- name: Stop default redis-server
  service: name=redis-server state=stopped
  tags:
    - redis

- name: Stop default sentinel
  service: name=redis-sentinel state=stopped
  tags:
    - redis

- include: server.yml
- include: sentinel.yml
- include: local_facts.yml